spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/outpatient?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
      date: dd/MM/yyyy
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 50MB
  sql:
    init:
      platform: mysql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  mapper-locations: classpath*:mapper/*.xml
aws:
  accessKey: 
  secretKey: 
#  endPoint: https://s3.amazonaws.com
  endPoint: https://s3.us-east-2.amazonaws.com
  bucketName: hospital-system-08
#  region: cn-east-1
  region: us-east-2